Vagrant.configure("2") do |config|
  config.vm.box = "generic/gentoo"

  config.vm.provision "shell", path: "./scripts/provision.sh"
  config.vm.provision "shell", path: "./scripts/install.sh"

  # config.vm.synced_folder ".", "/var/db/portage/rage", type: "sshfs", reverse: false

end
